name: sultan-susfs
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call: # This allows this workflow to be called from another workflow
    inputs:
      codename:
        required: true
        type: string
      repo:
        required: true
        type: string

  
jobs:
  sultan-susfs:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Install dependencies
        run: |
         sudo apt update
         sudo apt install -y \
          libssl-dev \
          libelf-dev \
          bc flex bison \
          libncurses-dev \
          gcc-aarch64-linux-gnu
          
      - name: Download Android toolchain
        run: |
          git clone --branch android-gs-shusky-6.1-android15-qpr2 --depth 1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang-prebuilts
          mv clang-prebuilts/clang-r487747c $HOME/toolchain
          #git clone --depth=1 --branch=llvm-r522817 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang-prebuilts
          #mv clang-prebuilts/clang-r522817 $HOME/toolchain
          #git clone --depth=1 --branch=llvm-r547379-release https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang-prebuilts
          #mv clang-prebuilts/clang-r547379 $HOME/toolchain

          

      - name: Set up environment variables
        run: |
          echo "PATH=$HOME/toolchain/bin:$PATH" >> $GITHUB_ENV
          echo "CONFIG=${{ inputs.repo }}" >> $GITHUB_ENV
          

      - name: Check compiler version
        run: clang --version 


        
      - name: Clone Repositories
        run: |
          echo "Clone Repositories"
          
          # Clone Repositories
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
          git clone https://github.com/spanish33/AnyKernel3.git -b 15.0.0-sultan-zuma
          git clone https://github.com/spanish33/patches.git
          git clone --depth=1 https://github.com/kerneltoast/${{ inputs.repo }} -b 15.0.0-sultan
      
      - name: Add KernelSU-Next
        run: |
          echo "Changing to configuration directory"
          cd "${{ env.CONFIG }}"
          echo "Adding KernelSU-Next..."
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

      - name: Apply SUSFS Patches
        run: |     
          # Copy SUSFS patches
          cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ${{ inputs.repo }}/
          cp ./susfs4ksu/kernel_patches/fs/* ${{ inputs.repo }}/fs/
          cp ./susfs4ksu/kernel_patches/include/linux/* ${{ inputs.repo }}/include/linux/
          cp ./patches/uname.patch ${{ inputs.repo }}/
          cp ./patches/fuze.patch ${{ inputs.repo }}/
          cp ./patches/safemode.patch ${{ inputs.repo }}/
          cp ./patches/0ctobot_hooks.patch ${{ inputs.repo }}/

          echo "Changing to configuration directory"
          cd "${{ env.CONFIG }}"
          echo "Applying SUSFS patches..."
          patch -p1 --forward < 50_add_susfs_in_gki-android14-6.1.patch || true
          patch -p0 --forward < uname.patch || true
          patch -p0 --forward < fuze.patch || true
          patch -p1 --forward < safemode.patch || true


      - name: Apply KSU Hooks from 0ctobot
        run: |
          echo "Applying hooks"
          cd "${{ env.CONFIG }}"
          patch -p1 --forward < 0ctobot_hooks.patch || true


      - name: Apply SUSFS Settings to Defconfig and Remove LTO
        run: |
          cd "${{ env.CONFIG }}"
          DEFCONFIG=arch/arm64/configs/${{ inputs.codename }}_defconfig
          # Remove existing conflicting LTO lines
          sed -i '/^CONFIG_LTO/d' $DEFCONFIG
          sed -i '/^CONFIG_LTO_GCC/d' $DEFCONFIG
          sed -i '/^CONFIG_LTO_CLANG/d' $DEFCONFIG
          sed -i '/^CONFIG_LTO_CLANG_THIN/d' $DEFCONFIG
          sed -i '/^CONFIG_LTO_CLANG_FULL/d' $DEFCONFIG
          sed -i '/^CONFIG_LTO_NONE/d' $DEFCONFIG

          # Add the CLANG LTO and SUSFS config
          echo "# CONFIG_LTO is not set" >> $DEFCONFIG
          echo "# CONFIG_LTO_CLANG is not set" >> $DEFCONFIG
          echo "# CONFIG_LTO_GCC is not set" >> $DEFCONFIG
          echo "# CONFIG_LTO_CLANG_THIN is not set" >> $DEFCONFIG
          echo "# CONFIG_LTO_CLANG_FULL is not set" >> $DEFCONFIG
          echo "# CONFIG_LTO_NONE is not set" >> $DEFCONFIG
          echo "CONFIG_KSU=y" >> $DEFCONFIG
          echo "CONFIG_KSU_WITH_KPROBES=n" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> $DEFCONFIG
          echo "CONFIG_TMPFS_XATTR=y" >> $DEFCONFIG

      - name: Change Kernel Name
        run: |
          echo "Changing to configuration directory"
          cd "${{ env.CONFIG }}"
          echo "Changing Kernel Name..."
          sed -i 's/CONFIG_LOCALVERSION="-Sultan"/CONFIG_LOCALVERSION="-android14-11-gd7dac4b14270-ab12946699"/' ./arch/arm64/configs/${{ inputs.codename }}_defconfig

      - name: Build the Kernel
        run: |
         cd "${{ env.CONFIG }}"
         make O=out ARCH=arm64 ${{ inputs.codename }}_defconfig
         
         # Export environment for make
         export PATH=$HOME/toolchain/bin:$PATH
         export CC=clang
         export LD=ld.lld
         export AR=llvm-ar
         export NM=llvm-nm
         export OBJCOPY=llvm-objcopy
         export OBJDUMP=llvm-objdump
         export STRIP=llvm-strip
         export LLVM=1
         export LLVM_IAS=1
         export CROSS_COMPILE=aarch64-linux-gnu-
         export HOSTLD=$HOME/toolchain/bin/ld.lld  
         export KCFLAGS="-Wno-missing-variable-declarations -Wno-unused-but-set-variable -Wno-error -Wno-unused-variable -Wno-unused-const-variable"
        
         make O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 \
         CROSS_COMPILE=aarch64-linux-gnu- \
         CC=clang \
         -j$(nproc) 2>&1 | tee build.log

      - name: Copy Images
        run: |
          cd "${{ env.CONFIG }}"
          cp out/arch/arm64/boot/Image.lz4 ../AnyKernel3/Image.lz4
          cat out/google-devices/zuma/dts/*.dtb > ../AnyKernel3/dtb

      - name: Create Flashable ZIP
        run: |
          cd AnyKernel3
          ZIP_NAME="Sultan_SUSFS_Clang.zip"
          zip -r "../$ZIP_NAME" ./*

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-zuma-clang
          path: |
            ./Sultan_SUSFS_Clang.zip
